apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ .Release.name }}
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name}}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
